<a href="https://colab.research.google.com/github/sashfaq911/Pytorch-Tutorial-Youtube/blob/Projects/Intro_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
2+2


4

## WHAT ARE TENSORS


*   A torch. Tensor is a milti-dimensional matrix containing elements of a single data type.
*   Similar to Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).
*   default data type of float32.
*   More suotable for deep learning than a nympy array.



In [2]:
import torch
import numpy as np


## LISTS

In [3]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

## NUMPY ARRAYS

In [4]:
 np1 = np.random.rand(3,4)
 np1

array([[0.57625658, 0.32500074, 0.28221623, 0.50690352],
       [0.56637174, 0.51507855, 0.39303509, 0.17242221],
       [0.52046127, 0.23110968, 0.8075734 , 0.39752256]])

In [5]:
np1.dtype

dtype('float64')

## TENSORS

In [6]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.2225,  2.1612,  0.5510,  1.2297],
        [-1.3093,  0.3365,  1.1102, -0.2698],
        [-0.3285, -1.3874,  1.2932,  0.6121]])

In [7]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.5763, 0.3250, 0.2822, 0.5069],
        [0.5664, 0.5151, 0.3930, 0.1724],
        [0.5205, 0.2311, 0.8076, 0.3975]], dtype=torch.float64)